# file: roles/vim/tasks/main.yml

- name: Vim | Make sure vim-tiny is uninstalled
  apt: pkg=vim-tiny state=absent purge=true
  when: ansible_os_family| lower == 'ubuntu'

- name: Vim | Make sure vim-nox is installed
  apt: pkg=vim-nox
  when: ansible_os_family| lower == 'ubuntu'
