# file: vagrant.yml

- name: Collecting facts
  hosts: vagrant
  gather_facts: yes

- hosts: all
  sudo: yes
  roles:
    - role: common
      tags:
        - common

# Zookeeper cluster deployment
- hosts: zookeeper
  sudo: yes
  roles:
  - role: zookeeper
    tags:
      - zookeeper

# Kafka cluster deployment
- hosts: kafka
  sudo: yes
  roles:
    - role: kafka
      tags:
        - kafka

# Redis cluster deployment
- hosts: redis
  sudo: yes
  vars:
    - redis_travis_ci: true
  roles:
    - redis

# Redis sentinel cluster deployment
- hosts: redis_sentinel
  sudo: yes
  roles:
    - redis

# Storm cluster deployment
- hosts: storm
  sudo: yes
  roles:
    - role: storm
      tags:
        - storm

- hosts: storm_nimbus
  sudo: yes
  roles:
    - role: storm_nimbus
      tags:
        - storm

- hosts: storm_supervisor
  sudo: yes
  roles:
    - role: storm_supervisor
      tags:
        - storm
