# file: roles/kafka/tasks/install.yml

# - name: Kafka | Download the kafka source from the git repo
#   git: repo={{ kafka_repo_url }} dest=/tmp/kafka-{{ kafka_version }} version={{ kafka_version }}
#
# - name: Kafka | Copy the kafka source in /opt
#   command: rsync --exclude ".git/" --exclude ".git*" -av --no-perms /tmp/kafka-{{ kafka_version }} /opt creates=/opt/kafka-{{ kafka_version }}
#
# - name: Kafka | Patch the kafka source for scala version compatibility
#   command: sed -i "s/2.8.0/{{ scala_version }}/g" bin/kafka-run-class.sh chdir=/opt/kafka-{{ kafka_version }}
#
# - name: Kafka | Package the kafka source - pt. 1
#   shell: ./sbt update chdir=/opt/kafka-{{ kafka_version }} creates=/opt/kafka-{{ kafka_version }}/target
#
# - name: Kafka | Package the kafka source - pt. 2
#   shell: ./sbt "++{{ scala_version }} package" chdir=/opt/kafka-{{ kafka_version }}
#
# - name: Kafka | Package the kafka source - pt. 3
#   shell: ./sbt "++{{ scala_version }} assembly-package-dependency" chdir=/opt/kafka-{{ kafka_version }}

- name: Kafka | Download the kafka source zip in /tmp if not yet present
  command: wget {{ kafka_mirror }}/apache/kafka/{{ kafka_version }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz chdir=/tmp creates=/tmp/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz

- name: Kafka | Unzip the kafka source in /opt
  command: tar -xzvf /tmp/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz chdir=/opt creates=/opt/kafka_{{ kafka_scala_version }}-{{ kafka_version }}

- name: Kafka | Update the kafka install permissions
  file: path=/opt/kafka_{{ kafka_scala_version }}-{{ kafka_version }} owner={{ kafka_user }} group={{ kafka_group }} state=directory recurse=yes

- name: Kafka | Update the symbolic link to the kafka install
  file: path=/opt/kafka src=/opt/kafka_{{ kafka_scala_version }}-{{ kafka_version }} state=link force=yes

- name: Kafka | Make sure the local working directory for kafka is present
  file: path={{ kafka_local_dir }} owner={{ kafka_user }} group={{ kafka_group }} mode=0750 state=directory
