# file: roles/timezone/tasks/redhat.yml

- name: Timezone | Make sure the dependencies are installed
  yum: name={{ item }} state=present
  with_items:
    - tzdata
    - ntp
    - ntpdate

- name: Timezone | Make sure ntpd is running and enabled
  service: name=ntpd state=restarted enabled=yes

- name: Timezone | Configure the ntp servers (/etc/ntp.conf)
  template: src=etc_ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntpd
