# file: roles/timezone/tasks/ubuntu.yml

- name: Timezone | Make sure the dependencies are installed
  apt: name={{ item }} state=installed
  with_items:
    - tzdata
    - ntp
    - ntpdate

- name: Timezone | Update the hardware clock
  command: dpkg-reconfigure -f noninteractive tzdata

- name: Timezone | Make sure ntpd is running and enabled
  service: name=ntp state=restarted enabled=yes

- name: Timezone | Configure the ntp servers (/etc/ntp.conf)
  template: src=etc_ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntp
